import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Code from '../components/Code'
import { Heading1, Heading2 } from '../components/Heading'

// map available components
const components = { Heading1, Heading2, Code };

// dummy json
const json = [
  {
    name: "Heading1",
    content: "This is some heading content for heading 1",
  },
  {
    name: "Heading2",
    content: "This is some other content for heading 2",
  },
  {
    name: "Code",
    content: "const test = 123",
    props: {
      language: "javascript"
    }
  }
];

// dynamic component
const DynamicComponent = (component:{ name: string; content: string; props?: {language?:string}}, i:number) => {
  const Component = components[component.name as keyof typeof components];
  const _props = component.props ? component.props : {}
  if (!Component) {
    console.error(`component ${component.name} was not found in component map`)
    return <></>;
  }
  return <Component key={i} content={component.content} props={_props}/>;
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Formation!</h1>
        {/* iterate over json, build right component */}
        <div>{json.map((component,i) => DynamicComponent(component,i))}</div>
      </main>
    </div>
  )
}

export default Home
